# Generated by Django 4.2.4 on 2023-08-20 10:20

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0003_remove_album_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=src.base.services.get_path_upload_cover_track, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='track',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
