# Generated by Django 4.2.4 on 2023-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0004_track_cover_track_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='track_playlist', to='audio_library.track'),
        ),
    ]
